package algomotors2;

import javax.swing.*;
import java.io.*;

public class AlgoFrame extends javax.swing.JFrame {

    // AlgoFrame constructor
    public AlgoFrame() {
        initComponents(); // loads initComponents constructor
        int carNum = 6; // There are 6 car types
        rentedCarCustomers = new String[carNum];
        carAvailability = new CarAvailability(carNum);
        updateRateNumField();
    }

    private CarAvailability carAvailability;
    private String[] rentedCarCustomers;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JTabbedPane();
        viewCarPanel = new javax.swing.JPanel();
        viewNestedCarTab = new javax.swing.JTabbedPane();
        viewNestedViosPanel = new javax.swing.JPanel();
        viosSpecsLabel = new javax.swing.JLabel();
        viosValuesLabel = new javax.swing.JLabel();
        viosEngineLabel = new javax.swing.JLabel();
        viosHorsepowerLabel = new javax.swing.JLabel();
        viosTransmissionLabel = new javax.swing.JLabel();
        viosTorqueLabel = new javax.swing.JLabel();
        viosHeightLabel = new javax.swing.JLabel();
        viosWidthLabel = new javax.swing.JLabel();
        viosLengthLabel = new javax.swing.JLabel();
        viosSeatingCapLabel = new javax.swing.JLabel();
        viosEngineValuesLabel = new javax.swing.JLabel();
        viosHorsepowerValuesLabel = new javax.swing.JLabel();
        viosTorqueValuesLabel = new javax.swing.JLabel();
        viosTransmissionValuesLabel = new javax.swing.JLabel();
        viosSeatingCapValuesLabel = new javax.swing.JLabel();
        viosLengthValuesLabel = new javax.swing.JLabel();
        viosVidthValuesLabel = new javax.swing.JLabel();
        viosHeightValuesLabel = new javax.swing.JLabel();
        viosIMGLabel = new javax.swing.JLabel();
        viewNestedAvanzaPanel = new javax.swing.JPanel();
        avanzaSpecsLabel = new javax.swing.JLabel();
        avanzaValuesLabel = new javax.swing.JLabel();
        avanzaEngineLabel = new javax.swing.JLabel();
        avanzaHorsepowerLabel = new javax.swing.JLabel();
        avanzaTorqueLabel = new javax.swing.JLabel();
        avanzaTransmissionLabel = new javax.swing.JLabel();
        avanzaSeatingCapLabel = new javax.swing.JLabel();
        avanzaLengthLabel = new javax.swing.JLabel();
        avanzaWidthlabel = new javax.swing.JLabel();
        avanzaHeightLabel = new javax.swing.JLabel();
        avanzaHeightValuesLabel = new javax.swing.JLabel();
        avanzaWidthValuesLabel = new javax.swing.JLabel();
        avanzaLengthValueslabel = new javax.swing.JLabel();
        avanzaSeatingCapValuesLabel = new javax.swing.JLabel();
        avanzaTransmissionValuesLabel = new javax.swing.JLabel();
        avanzaTorqueValuesLabel = new javax.swing.JLabel();
        avanzaHorsepowerValuesLabel = new javax.swing.JLabel();
        avanzaEngineValuesLabel = new javax.swing.JLabel();
        avanzaIMGLabel = new javax.swing.JLabel();
        viewNestedCorollaPanel = new javax.swing.JPanel();
        corollaSpecsLabel = new javax.swing.JLabel();
        corollaValuesLabel = new javax.swing.JLabel();
        corollaEngineLabel = new javax.swing.JLabel();
        corollaHorsepowerLabel = new javax.swing.JLabel();
        corollaTorqueLabel = new javax.swing.JLabel();
        corollaTransmissionLabel = new javax.swing.JLabel();
        corollaSeatingCapLabel = new javax.swing.JLabel();
        corollaLengthLabel = new javax.swing.JLabel();
        corollaWidthLabel = new javax.swing.JLabel();
        corollaHeightLabel = new javax.swing.JLabel();
        corollaEngineValuesLabel = new javax.swing.JLabel();
        corollaHorsepowerValuesLabel = new javax.swing.JLabel();
        corollaTorqueValuesLabel = new javax.swing.JLabel();
        corollaTransmissionValuesLabel = new javax.swing.JLabel();
        corollaSeatingCapValuesLabel = new javax.swing.JLabel();
        corollaLengthValuesLabel = new javax.swing.JLabel();
        corollaWidthValuesLabel = new javax.swing.JLabel();
        corollaHeightValuesLabel = new javax.swing.JLabel();
        corollaIMGLabel = new javax.swing.JLabel();
        viewNestedInnovaPanel = new javax.swing.JPanel();
        innovaSpecsLabel = new javax.swing.JLabel();
        innovaValuesLabel = new javax.swing.JLabel();
        innovaEngineLabel = new javax.swing.JLabel();
        innovaHorsepowerLabel3 = new javax.swing.JLabel();
        innovaTorqueLabel = new javax.swing.JLabel();
        innovaTransmissionLabel = new javax.swing.JLabel();
        innovaSeatingCapLabel = new javax.swing.JLabel();
        innovaLengthLabel = new javax.swing.JLabel();
        innovaWidthLabel = new javax.swing.JLabel();
        innovaHeightLabel = new javax.swing.JLabel();
        innovaEngineValuesLabel = new javax.swing.JLabel();
        innovaHorsepowerValuesLabel = new javax.swing.JLabel();
        innovaTorqueValuesLabel = new javax.swing.JLabel();
        innovaTransmissionValuesLabel = new javax.swing.JLabel();
        innovaSeatingCapValuesLabel = new javax.swing.JLabel();
        innovaLengthValuesLabel = new javax.swing.JLabel();
        innovaWidthValuesLabel = new javax.swing.JLabel();
        heightValuesLabel3 = new javax.swing.JLabel();
        innovaIMGLabel = new javax.swing.JLabel();
        viewNestedHiluxPanel = new javax.swing.JPanel();
        hiluxSpecsLabel = new javax.swing.JLabel();
        hiluxValuesLabel = new javax.swing.JLabel();
        hiluxEngineLabel = new javax.swing.JLabel();
        hiluxHorsepowerLabel = new javax.swing.JLabel();
        hiluxTorqueLabel = new javax.swing.JLabel();
        hiluxTransmissionLabel = new javax.swing.JLabel();
        hiluxSeatingCapLabel = new javax.swing.JLabel();
        hiluxLengthLabel = new javax.swing.JLabel();
        hiluxWidthLabel = new javax.swing.JLabel();
        hiluxHeightLabel = new javax.swing.JLabel();
        hiluxEngineValuesLabel = new javax.swing.JLabel();
        hiluxHorsepowerValuesLabel = new javax.swing.JLabel();
        hiluxTorqueValuesLabel = new javax.swing.JLabel();
        hiluxTransmissionValuesLabel = new javax.swing.JLabel();
        hiluxSeatingCapValuesLabel = new javax.swing.JLabel();
        hiluxLengthValuesLabel = new javax.swing.JLabel();
        hiluxWidthValuesLabel = new javax.swing.JLabel();
        hiluxHeightValuesLabel = new javax.swing.JLabel();
        hiluxIMGLabel = new javax.swing.JLabel();
        viewNestedFortunerPanel = new javax.swing.JPanel();
        fortunerSpecsLabel = new javax.swing.JLabel();
        fortunerValuesLabel = new javax.swing.JLabel();
        fortunerEngineLabel = new javax.swing.JLabel();
        fortunerHorsepowerLabel = new javax.swing.JLabel();
        fortunerTorqueLabel = new javax.swing.JLabel();
        fortunerTransmissionLabel = new javax.swing.JLabel();
        fortunerSeatingCapLabel = new javax.swing.JLabel();
        fortunerLengthLabel = new javax.swing.JLabel();
        fortunerWidthLabel = new javax.swing.JLabel();
        fortunerHeightLabel = new javax.swing.JLabel();
        fortunerEngineValuesLabel = new javax.swing.JLabel();
        fortunerHorsepowerValuesLabel = new javax.swing.JLabel();
        fortunerTorqueValuesLabel = new javax.swing.JLabel();
        fortunerTransmissionValuesLabel = new javax.swing.JLabel();
        fortunerSeatingCapValuesLabel = new javax.swing.JLabel();
        fortunerLengthValuesLabel = new javax.swing.JLabel();
        fortunerWidthValuesLabel = new javax.swing.JLabel();
        fortunerHeightValuesLabel = new javax.swing.JLabel();
        fortunerIMGLabel = new javax.swing.JLabel();
        rentACarPanel = new javax.swing.JPanel();
        rentNameLabel = new javax.swing.JLabel();
        rentNameField = new javax.swing.JTextField();
        rentModelLabel = new javax.swing.JLabel();
        rentCarCombo = new javax.swing.JComboBox<>();
        rentCarButton = new javax.swing.JButton();
        rentAmountLabel = new javax.swing.JLabel();
        rentAmountField = new javax.swing.JTextField();
        rentDaysLabel = new javax.swing.JLabel();
        rentDaysField = new javax.swing.JTextField();
        rateHeaderLabel = new javax.swing.JLabel();
        rateNumField = new javax.swing.JTextField();
        rentTotalField = new javax.swing.JTextField();
        rentChangeField = new javax.swing.JTextField();
        rentTotalButton = new javax.swing.JButton();
        rentChangeButton = new javax.swing.JButton();
        rentTotalLabel = new javax.swing.JLabel();
        rentChangeLabel = new javax.swing.JLabel();
        rentClearButton = new javax.swing.JButton();
        returnACarPanel = new javax.swing.JPanel();
        returnModelLabel = new javax.swing.JLabel();
        returnCarCombo = new javax.swing.JComboBox<>();
        returnNameLabel = new javax.swing.JLabel();
        returnNameField = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        statusPane = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();
        titleHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algo Motors");

        viosSpecsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viosSpecsLabel.setText("SPECIFICATIONS");

        viosValuesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viosValuesLabel.setText("VALUES");

        viosEngineLabel.setText("Engine");

        viosHorsepowerLabel.setText("Horsepower");

        viosTransmissionLabel.setText("Transmission");

        viosTorqueLabel.setText("Torque");

        viosHeightLabel.setText("Height");

        viosWidthLabel.setText("Width");

        viosLengthLabel.setText("Length");

        viosSeatingCapLabel.setText("Seating Capacity");

        viosEngineValuesLabel.setText("1.5-liter 4-cylinder gasoline engine");

        viosHorsepowerValuesLabel.setText("90");

        viosTorqueValuesLabel.setText("120 Nm");

        viosTransmissionValuesLabel.setText("5-speed manual");

        viosSeatingCapValuesLabel.setText("5");

        viosLengthValuesLabel.setText("4,425mm");

        viosVidthValuesLabel.setText("1,740mm");

        viosHeightValuesLabel.setText("1,480mm");

        viosIMGLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algomotors2/Vios.jpg"))); // NOI18N
        viosIMGLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout viewNestedViosPanelLayout = new javax.swing.GroupLayout(viewNestedViosPanel);
        viewNestedViosPanel.setLayout(viewNestedViosPanelLayout);
        viewNestedViosPanelLayout.setHorizontalGroup(
            viewNestedViosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedViosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewNestedViosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viosSpecsLabel)
                    .addComponent(viosHorsepowerLabel)
                    .addComponent(viosTorqueLabel)
                    .addComponent(viosTransmissionLabel)
                    .addComponent(viosSeatingCapLabel)
                    .addComponent(viosLengthLabel)
                    .addComponent(viosWidthLabel)
                    .addComponent(viosHeightLabel)
                    .addComponent(viosEngineLabel))
                .addGap(38, 38, 38)
                .addGroup(viewNestedViosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viosValuesLabel)
                    .addComponent(viosHorsepowerValuesLabel)
                    .addComponent(viosTorqueValuesLabel)
                    .addComponent(viosTransmissionValuesLabel)
                    .addComponent(viosSeatingCapValuesLabel)
                    .addComponent(viosLengthValuesLabel)
                    .addComponent(viosVidthValuesLabel)
                    .addComponent(viosHeightValuesLabel)
                    .addComponent(viosEngineValuesLabel))
                .addGap(28, 28, 28)
                .addComponent(viosIMGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewNestedViosPanelLayout.setVerticalGroup(
            viewNestedViosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedViosPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(viewNestedViosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viosIMGLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewNestedViosPanelLayout.createSequentialGroup()
                        .addGroup(viewNestedViosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viosSpecsLabel)
                            .addComponent(viosValuesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewNestedViosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewNestedViosPanelLayout.createSequentialGroup()
                                .addComponent(viosEngineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosHorsepowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosTorqueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosTransmissionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosSeatingCapLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosLengthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosWidthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosHeightLabel))
                            .addGroup(viewNestedViosPanelLayout.createSequentialGroup()
                                .addComponent(viosEngineValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosHorsepowerValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosTorqueValuesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosTransmissionValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosSeatingCapValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosLengthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosVidthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viosHeightValuesLabel)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        viewNestedCarTab.addTab("Vios", viewNestedViosPanel);

        avanzaSpecsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        avanzaSpecsLabel.setText("SPECIFICATIONS");

        avanzaValuesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        avanzaValuesLabel.setText("VALUES");

        avanzaEngineLabel.setText("Engine");

        avanzaHorsepowerLabel.setText("Horsepower");

        avanzaTorqueLabel.setText("Torque");

        avanzaTransmissionLabel.setText("Transmission");

        avanzaSeatingCapLabel.setText("Seating Capacity");

        avanzaLengthLabel.setText("Length");

        avanzaWidthlabel.setText("Width");

        avanzaHeightLabel.setText("Height");

        avanzaHeightValuesLabel.setText("1,695mm");

        avanzaWidthValuesLabel.setText("1,660mm");

        avanzaLengthValueslabel.setText("4,190mm");

        avanzaSeatingCapValuesLabel.setText("7");

        avanzaTransmissionValuesLabel.setText("5-speed manual");

        avanzaTorqueValuesLabel.setText("136 Nm");

        avanzaHorsepowerValuesLabel.setText("103");

        avanzaEngineValuesLabel.setText("1.5-liter 4-cylinder gasoline engine");

        avanzaIMGLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algomotors2/Avanza.jpg"))); // NOI18N
        avanzaIMGLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout viewNestedAvanzaPanelLayout = new javax.swing.GroupLayout(viewNestedAvanzaPanel);
        viewNestedAvanzaPanel.setLayout(viewNestedAvanzaPanelLayout);
        viewNestedAvanzaPanelLayout.setHorizontalGroup(
            viewNestedAvanzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedAvanzaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewNestedAvanzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avanzaSpecsLabel)
                    .addComponent(avanzaHorsepowerLabel)
                    .addComponent(avanzaTorqueLabel)
                    .addComponent(avanzaTransmissionLabel)
                    .addComponent(avanzaSeatingCapLabel)
                    .addComponent(avanzaLengthLabel)
                    .addComponent(avanzaWidthlabel)
                    .addComponent(avanzaHeightLabel)
                    .addComponent(avanzaEngineLabel))
                .addGap(38, 38, 38)
                .addGroup(viewNestedAvanzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avanzaValuesLabel)
                    .addComponent(avanzaHorsepowerValuesLabel)
                    .addComponent(avanzaTorqueValuesLabel)
                    .addComponent(avanzaTransmissionValuesLabel)
                    .addComponent(avanzaSeatingCapValuesLabel)
                    .addComponent(avanzaLengthValueslabel)
                    .addComponent(avanzaWidthValuesLabel)
                    .addComponent(avanzaHeightValuesLabel)
                    .addComponent(avanzaEngineValuesLabel))
                .addGap(28, 28, 28)
                .addComponent(avanzaIMGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewNestedAvanzaPanelLayout.setVerticalGroup(
            viewNestedAvanzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedAvanzaPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(viewNestedAvanzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avanzaIMGLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewNestedAvanzaPanelLayout.createSequentialGroup()
                        .addGroup(viewNestedAvanzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(avanzaSpecsLabel)
                            .addComponent(avanzaValuesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewNestedAvanzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewNestedAvanzaPanelLayout.createSequentialGroup()
                                .addComponent(avanzaEngineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaHorsepowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaTorqueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaTransmissionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaSeatingCapLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaLengthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaWidthlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaHeightLabel))
                            .addGroup(viewNestedAvanzaPanelLayout.createSequentialGroup()
                                .addComponent(avanzaEngineValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaHorsepowerValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaTorqueValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaTransmissionValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaSeatingCapValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaLengthValueslabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaWidthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avanzaHeightValuesLabel)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        viewNestedCarTab.addTab("Avanza", viewNestedAvanzaPanel);

        corollaSpecsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        corollaSpecsLabel.setText("SPECIFICATIONS");

        corollaValuesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        corollaValuesLabel.setText("VALUES");

        corollaEngineLabel.setText("Engine");

        corollaHorsepowerLabel.setText("Horsepower");

        corollaTorqueLabel.setText("Torque");

        corollaTransmissionLabel.setText("Transmission");

        corollaSeatingCapLabel.setText("Seating Capacity");

        corollaLengthLabel.setText("Length");

        corollaWidthLabel.setText("Width");

        corollaHeightLabel.setText("Height");

        corollaEngineValuesLabel.setText("2.0-liter inline 4 gasoline engine");

        corollaHorsepowerValuesLabel.setText("169");

        corollaTorqueValuesLabel.setText("151 Nm");

        corollaTransmissionValuesLabel.setText("variable-speed automatic");

        corollaSeatingCapValuesLabel.setText("5");

        corollaLengthValuesLabel.setText("4,638mm");

        corollaWidthValuesLabel.setText("1,781mm");

        corollaHeightValuesLabel.setText("1,435mm");

        corollaIMGLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algomotors2/Corolla.jpg"))); // NOI18N
        corollaIMGLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout viewNestedCorollaPanelLayout = new javax.swing.GroupLayout(viewNestedCorollaPanel);
        viewNestedCorollaPanel.setLayout(viewNestedCorollaPanelLayout);
        viewNestedCorollaPanelLayout.setHorizontalGroup(
            viewNestedCorollaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedCorollaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewNestedCorollaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corollaSpecsLabel)
                    .addComponent(corollaHorsepowerLabel)
                    .addComponent(corollaTorqueLabel)
                    .addComponent(corollaTransmissionLabel)
                    .addComponent(corollaSeatingCapLabel)
                    .addComponent(corollaLengthLabel)
                    .addComponent(corollaWidthLabel)
                    .addComponent(corollaHeightLabel)
                    .addComponent(corollaEngineLabel))
                .addGap(38, 38, 38)
                .addGroup(viewNestedCorollaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corollaValuesLabel)
                    .addComponent(corollaHorsepowerValuesLabel)
                    .addComponent(corollaTorqueValuesLabel)
                    .addComponent(corollaTransmissionValuesLabel)
                    .addComponent(corollaSeatingCapValuesLabel)
                    .addComponent(corollaLengthValuesLabel)
                    .addComponent(corollaWidthValuesLabel)
                    .addComponent(corollaHeightValuesLabel)
                    .addComponent(corollaEngineValuesLabel))
                .addGap(43, 43, 43)
                .addComponent(corollaIMGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewNestedCorollaPanelLayout.setVerticalGroup(
            viewNestedCorollaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedCorollaPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(viewNestedCorollaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(corollaIMGLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewNestedCorollaPanelLayout.createSequentialGroup()
                        .addGroup(viewNestedCorollaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(corollaSpecsLabel)
                            .addComponent(corollaValuesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewNestedCorollaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewNestedCorollaPanelLayout.createSequentialGroup()
                                .addComponent(corollaEngineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaHorsepowerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaTorqueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaTransmissionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaSeatingCapLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaLengthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaWidthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaHeightLabel))
                            .addGroup(viewNestedCorollaPanelLayout.createSequentialGroup()
                                .addComponent(corollaEngineValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaHorsepowerValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaTorqueValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaTransmissionValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaSeatingCapValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaLengthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaWidthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(corollaHeightValuesLabel)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        viewNestedCarTab.addTab("Corolla", viewNestedCorollaPanel);

        innovaSpecsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        innovaSpecsLabel.setText("SPECIFICATIONS");

        innovaValuesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        innovaValuesLabel.setText("VALUES");

        innovaEngineLabel.setText("Engine");

        innovaHorsepowerLabel3.setText("Horsepower");

        innovaTorqueLabel.setText("Torque");

        innovaTransmissionLabel.setText("Transmission");

        innovaSeatingCapLabel.setText("Seating Capacity");

        innovaLengthLabel.setText("Length");

        innovaWidthLabel.setText("Width");

        innovaHeightLabel.setText("Height");

        innovaEngineValuesLabel.setText("1.5-liter 4-cylinder gasoline engine");

        innovaHorsepowerValuesLabel.setText("103");

        innovaTorqueValuesLabel.setText("136 Nm");

        innovaTransmissionValuesLabel.setText("5-speed manual");

        innovaSeatingCapValuesLabel.setText("7");

        innovaLengthValuesLabel.setText("4,190mm");

        innovaWidthValuesLabel.setText("1,660mm");

        heightValuesLabel3.setText("1,695mm");

        innovaIMGLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algomotors2/Innova.jpg"))); // NOI18N
        innovaIMGLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout viewNestedInnovaPanelLayout = new javax.swing.GroupLayout(viewNestedInnovaPanel);
        viewNestedInnovaPanel.setLayout(viewNestedInnovaPanelLayout);
        viewNestedInnovaPanelLayout.setHorizontalGroup(
            viewNestedInnovaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedInnovaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewNestedInnovaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(innovaSpecsLabel)
                    .addComponent(innovaHorsepowerLabel3)
                    .addComponent(innovaTorqueLabel)
                    .addComponent(innovaTransmissionLabel)
                    .addComponent(innovaSeatingCapLabel)
                    .addComponent(innovaLengthLabel)
                    .addComponent(innovaWidthLabel)
                    .addComponent(innovaHeightLabel)
                    .addComponent(innovaEngineLabel))
                .addGap(38, 38, 38)
                .addGroup(viewNestedInnovaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(innovaValuesLabel)
                    .addComponent(innovaHorsepowerValuesLabel)
                    .addComponent(innovaTorqueValuesLabel)
                    .addComponent(innovaTransmissionValuesLabel)
                    .addComponent(innovaSeatingCapValuesLabel)
                    .addComponent(innovaLengthValuesLabel)
                    .addComponent(innovaWidthValuesLabel)
                    .addComponent(heightValuesLabel3)
                    .addComponent(innovaEngineValuesLabel))
                .addGap(28, 28, 28)
                .addComponent(innovaIMGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewNestedInnovaPanelLayout.setVerticalGroup(
            viewNestedInnovaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedInnovaPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(viewNestedInnovaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(innovaIMGLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewNestedInnovaPanelLayout.createSequentialGroup()
                        .addGroup(viewNestedInnovaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(innovaSpecsLabel)
                            .addComponent(innovaValuesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewNestedInnovaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewNestedInnovaPanelLayout.createSequentialGroup()
                                .addComponent(innovaEngineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaHorsepowerLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaTorqueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaTransmissionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaSeatingCapLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaLengthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaWidthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaHeightLabel))
                            .addGroup(viewNestedInnovaPanelLayout.createSequentialGroup()
                                .addComponent(innovaEngineValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaHorsepowerValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaTorqueValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaTransmissionValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaSeatingCapValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaLengthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(innovaWidthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heightValuesLabel3)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        viewNestedCarTab.addTab("Innova", viewNestedInnovaPanel);

        hiluxSpecsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hiluxSpecsLabel.setText("SPECIFICATIONS");

        hiluxValuesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hiluxValuesLabel.setText("VALUES");

        hiluxEngineLabel.setText("Engine");

        hiluxHorsepowerLabel.setText("Horsepower");

        hiluxTorqueLabel.setText("Torque");

        hiluxTransmissionLabel.setText("Transmission");

        hiluxSeatingCapLabel.setText("Seating Capacity");

        hiluxLengthLabel.setText("Length");

        hiluxWidthLabel.setText("Width");

        hiluxHeightLabel.setText("Height");

        hiluxEngineValuesLabel.setText("2.4-liter diesel");

        hiluxHorsepowerValuesLabel.setText("148");

        hiluxTorqueValuesLabel.setText("400 Nm");

        hiluxTransmissionValuesLabel.setText("6-speed manual/automatic");

        hiluxSeatingCapValuesLabel.setText("5");

        hiluxLengthValuesLabel.setText("5,270mm");

        hiluxWidthValuesLabel.setText("1,800mm");

        hiluxHeightValuesLabel.setText("1,795mm");

        hiluxIMGLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algomotors2/Hilux.jpg"))); // NOI18N
        hiluxIMGLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout viewNestedHiluxPanelLayout = new javax.swing.GroupLayout(viewNestedHiluxPanel);
        viewNestedHiluxPanel.setLayout(viewNestedHiluxPanelLayout);
        viewNestedHiluxPanelLayout.setHorizontalGroup(
            viewNestedHiluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedHiluxPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewNestedHiluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiluxSpecsLabel)
                    .addComponent(hiluxHorsepowerLabel)
                    .addComponent(hiluxTorqueLabel)
                    .addComponent(hiluxTransmissionLabel)
                    .addComponent(hiluxSeatingCapLabel)
                    .addComponent(hiluxLengthLabel)
                    .addComponent(hiluxWidthLabel)
                    .addComponent(hiluxHeightLabel)
                    .addComponent(hiluxEngineLabel))
                .addGap(38, 38, 38)
                .addGroup(viewNestedHiluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiluxValuesLabel)
                    .addComponent(hiluxHorsepowerValuesLabel)
                    .addComponent(hiluxTorqueValuesLabel)
                    .addComponent(hiluxTransmissionValuesLabel)
                    .addComponent(hiluxSeatingCapValuesLabel)
                    .addComponent(hiluxLengthValuesLabel)
                    .addComponent(hiluxWidthValuesLabel)
                    .addComponent(hiluxHeightValuesLabel)
                    .addComponent(hiluxEngineValuesLabel))
                .addGap(66, 66, 66)
                .addComponent(hiluxIMGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewNestedHiluxPanelLayout.setVerticalGroup(
            viewNestedHiluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedHiluxPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(viewNestedHiluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hiluxIMGLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewNestedHiluxPanelLayout.createSequentialGroup()
                        .addGroup(viewNestedHiluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hiluxSpecsLabel)
                            .addComponent(hiluxValuesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewNestedHiluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewNestedHiluxPanelLayout.createSequentialGroup()
                                .addComponent(hiluxEngineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxHorsepowerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxTorqueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxTransmissionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxSeatingCapLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxLengthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxWidthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxHeightLabel))
                            .addGroup(viewNestedHiluxPanelLayout.createSequentialGroup()
                                .addComponent(hiluxEngineValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxHorsepowerValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxTorqueValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxTransmissionValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxSeatingCapValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxLengthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxWidthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hiluxHeightValuesLabel)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        viewNestedCarTab.addTab("Hilux", viewNestedHiluxPanel);

        fortunerSpecsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fortunerSpecsLabel.setText("SPECIFICATIONS");

        fortunerValuesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fortunerValuesLabel.setText("VALUES");

        fortunerEngineLabel.setText("Engine");

        fortunerHorsepowerLabel.setText("Horsepower");

        fortunerTorqueLabel.setText("Torque");

        fortunerTransmissionLabel.setText("Transmission");

        fortunerSeatingCapLabel.setText("Seating Capacity");

        fortunerLengthLabel.setText("Length");

        fortunerWidthLabel.setText("Width");

        fortunerHeightLabel.setText("Height");

        fortunerEngineValuesLabel.setText("2.7-liter 4-cylinder gasoline engine");

        fortunerHorsepowerValuesLabel.setText("164");

        fortunerTorqueValuesLabel.setText("245 Nm");

        fortunerTransmissionValuesLabel.setText("Automatic");

        fortunerSeatingCapValuesLabel.setText("7");

        fortunerLengthValuesLabel.setText("4,795mm");

        fortunerWidthValuesLabel.setText("1,885mm");

        fortunerHeightValuesLabel.setText("1,835mm");

        fortunerIMGLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algomotors2/Fortuner.jpg"))); // NOI18N
        fortunerIMGLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout viewNestedFortunerPanelLayout = new javax.swing.GroupLayout(viewNestedFortunerPanel);
        viewNestedFortunerPanel.setLayout(viewNestedFortunerPanelLayout);
        viewNestedFortunerPanelLayout.setHorizontalGroup(
            viewNestedFortunerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedFortunerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewNestedFortunerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fortunerSpecsLabel)
                    .addComponent(fortunerHorsepowerLabel)
                    .addComponent(fortunerTorqueLabel)
                    .addComponent(fortunerTransmissionLabel)
                    .addComponent(fortunerSeatingCapLabel)
                    .addComponent(fortunerLengthLabel)
                    .addComponent(fortunerWidthLabel)
                    .addComponent(fortunerHeightLabel)
                    .addComponent(fortunerEngineLabel))
                .addGap(38, 38, 38)
                .addGroup(viewNestedFortunerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fortunerTransmissionValuesLabel)
                    .addComponent(fortunerSeatingCapValuesLabel)
                    .addComponent(fortunerLengthValuesLabel)
                    .addComponent(fortunerWidthValuesLabel)
                    .addComponent(fortunerHeightValuesLabel)
                    .addComponent(fortunerValuesLabel)
                    .addComponent(fortunerEngineValuesLabel)
                    .addComponent(fortunerHorsepowerValuesLabel)
                    .addComponent(fortunerTorqueValuesLabel))
                .addGap(28, 28, 28)
                .addComponent(fortunerIMGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewNestedFortunerPanelLayout.setVerticalGroup(
            viewNestedFortunerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewNestedFortunerPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(viewNestedFortunerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fortunerIMGLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(viewNestedFortunerPanelLayout.createSequentialGroup()
                        .addGroup(viewNestedFortunerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fortunerSpecsLabel)
                            .addComponent(fortunerValuesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewNestedFortunerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewNestedFortunerPanelLayout.createSequentialGroup()
                                .addComponent(fortunerEngineLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerHorsepowerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerTorqueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerTransmissionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerSeatingCapLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerLengthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerWidthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerHeightLabel))
                            .addGroup(viewNestedFortunerPanelLayout.createSequentialGroup()
                                .addComponent(fortunerEngineValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerHorsepowerValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerTorqueValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerTransmissionValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerSeatingCapValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerLengthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerWidthValuesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fortunerHeightValuesLabel)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        viewNestedCarTab.addTab("Fortuner", viewNestedFortunerPanel);

        javax.swing.GroupLayout viewCarPanelLayout = new javax.swing.GroupLayout(viewCarPanel);
        viewCarPanel.setLayout(viewCarPanelLayout);
        viewCarPanelLayout.setHorizontalGroup(
            viewCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewNestedCarTab)
                .addContainerGap())
        );
        viewCarPanelLayout.setVerticalGroup(
            viewCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewNestedCarTab)
                .addContainerGap())
        );

        mainPanel.addTab("View Cars", viewCarPanel);

        rentNameLabel.setText("Name");

        rentModelLabel.setText("Model");

        rentCarCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vios", "Avanza", "Corolla", "Innova", "Hilux", "Fortuner" }));
        rentCarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarComboActionPerformed(evt);
            }
        });

        rentCarButton.setText("Rent Car");
        rentCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarButtonActionPerformed(evt);
            }
        });

        rentAmountLabel.setText("Amount");

        rentAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentAmountFieldActionPerformed(evt);
            }
        });

        rentDaysLabel.setText("Day/s to Rent");

        rentDaysField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentDaysFieldActionPerformed(evt);
            }
        });

        rateHeaderLabel.setText("Rate per day");

        rateNumField.setEditable(false);

        rentTotalField.setEditable(false);

        rentChangeField.setEditable(false);

        rentTotalButton.setText("Get Rent");
        rentTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentTotalButtonActionPerformed(evt);
            }
        });

        rentChangeButton.setText("Get Change");
        rentChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentChangeButtonActionPerformed(evt);
            }
        });

        rentTotalLabel.setText("Rent Total");

        rentChangeLabel.setText("Change Tendered");

        rentClearButton.setText("Clear All Fields");
        rentClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentACarPanelLayout = new javax.swing.GroupLayout(rentACarPanel);
        rentACarPanel.setLayout(rentACarPanelLayout);
        rentACarPanelLayout.setHorizontalGroup(
            rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentACarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentACarPanelLayout.createSequentialGroup()
                        .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentNameLabel)
                            .addComponent(rentModelLabel)
                            .addComponent(rentDaysLabel)
                            .addComponent(rentTotalLabel)
                            .addComponent(rentAmountLabel))
                        .addGap(40, 40, 40)
                        .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentNameField)
                            .addGroup(rentACarPanelLayout.createSequentialGroup()
                                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rentACarPanelLayout.createSequentialGroup()
                                        .addComponent(rentAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rentChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(rentACarPanelLayout.createSequentialGroup()
                                        .addComponent(rentDaysField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rentTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rentTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(rentACarPanelLayout.createSequentialGroup()
                                        .addComponent(rentCarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rateHeaderLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(rateNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 272, Short.MAX_VALUE))))
                    .addGroup(rentACarPanelLayout.createSequentialGroup()
                        .addComponent(rentChangeLabel)
                        .addGap(18, 18, 18)
                        .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentChangeField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rentACarPanelLayout.createSequentialGroup()
                                .addComponent(rentCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rentClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        rentACarPanelLayout.setVerticalGroup(
            rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentACarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentNameLabel)
                    .addComponent(rentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentModelLabel)
                    .addComponent(rentCarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateHeaderLabel)
                    .addComponent(rateNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentDaysField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentDaysLabel)
                    .addComponent(rentTotalButton))
                .addGap(18, 18, 18)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentTotalLabel)
                    .addComponent(rentTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentAmountLabel)
                    .addComponent(rentAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentChangeButton))
                .addGap(18, 18, 18)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentChangeLabel)
                    .addComponent(rentChangeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        mainPanel.addTab("Rent A Car", rentACarPanel);

        returnModelLabel.setText("Model");

        returnCarCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vios", "Avanza", "Corolla", "Innova", "Hilux", "Fortuner" }));

        returnNameLabel.setText("Name");

        returnButton.setText("Return Car");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnACarPanelLayout = new javax.swing.GroupLayout(returnACarPanel);
        returnACarPanel.setLayout(returnACarPanelLayout);
        returnACarPanelLayout.setHorizontalGroup(
            returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnACarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnACarPanelLayout.createSequentialGroup()
                        .addComponent(returnNameLabel)
                        .addGap(79, 79, 79)
                        .addComponent(returnNameField))
                    .addGroup(returnACarPanelLayout.createSequentialGroup()
                        .addGroup(returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnACarPanelLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(returnACarPanelLayout.createSequentialGroup()
                                .addComponent(returnModelLabel)
                                .addGap(77, 77, 77)
                                .addComponent(returnCarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 460, Short.MAX_VALUE)))
                .addContainerGap())
        );
        returnACarPanelLayout.setVerticalGroup(
            returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnACarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnNameLabel)
                    .addComponent(returnNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnModelLabel)
                    .addComponent(returnCarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        mainPanel.addTab("Return A Car", returnACarPanel);

        statusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Vios", null, null},
                {"Avanza", null, null},
                {"Corolla", null, null},
                {"Innova", null, null},
                {"Hilux", null, null},
                {"Fortuner", null, null}
            },
            new String [] {
                "Model", "Is Rented", "Tenant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        statusPane.setViewportView(statusTable);

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusPane, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusPane, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        mainPanel.addTab("Status Panel", statusPanel);

        titleHeader.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleHeader.setText("ALGO MOTORS SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleHeader)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleHeader)
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ------------ EVENTS START ------------
    // RETURN BUTTON : RETURN A CAR : OUTPUT RETURNED CAR
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        try {
            // Check if nameReturnField is not blank
            if (returnNameField.getText().trim().isEmpty()) {
                throw new InvalidReturnException("Name cannot be blank.");
            }

            returnCar();
        } catch (InvalidReturnException e) {
            // Handle the exception, e.g., display an error message
            JOptionPane.showMessageDialog(this, e.getMessage(), "Invalid return: The car cannot be returned.", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_returnButtonActionPerformed

    // CHANGE NUM BUTTON : RENT A CAR : OUTPUT CHANGE FROM AMOUNT
    private void rentChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentChangeButtonActionPerformed
        calculateChange();
    }//GEN-LAST:event_rentChangeButtonActionPerformed

    // RENT TOTAL BUTTON : RENT A CAR : OUTPUT RENT
    private void rentTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentTotalButtonActionPerformed
        calculateRentTotal(); // part of calculateRentTotal()
    }//GEN-LAST:event_rentTotalButtonActionPerformed

    // DAYS RENT FIELD : RENT A CAR : INPUT HOW MANY DAYS TO RENT
    private void rentDaysFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentDaysFieldActionPerformed
        calculateRentTotal(); // part of calculateRentTotal()
    }//GEN-LAST:event_rentDaysFieldActionPerformed

    // AMOUNT FIELD : RENT A CAR :  INPUT HOW MUCH TO PAY FOR
    private void rentAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentAmountFieldActionPerformed
        calculateChange();
    }//GEN-LAST:event_rentAmountFieldActionPerformed

    // RENT CAR BUTTON : RENT A CAR : OUTPUT THE RENT SUCCESS OUTPUT
    private void rentCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarButtonActionPerformed
        // try multiple exceptions
        try {

            // Check if name is not blank
            if (rentNameField.getText().trim().isEmpty()) {
                throw new InvalidRentException("Invalid. Check if blank or invalid format.");
            }

            // Check if daysRentField is neither blank, 0, nor invalid
            try {
                int days = Integer.parseInt(rentDaysField.getText());
                if (days <= 0) {
                    throw new InvalidRentException("Days must be greater than 0.");
                }
            } catch (NumberFormatException e) {
                throw new InvalidRentException("Invalid. Must be whole numbers only.");
            }

            // Check if changeNumField is neither blank nor invalid
            try {
                Integer.parseInt(rentChangeField.getText());
            } catch (NumberFormatException e) {
                throw new InvalidRentException("Invalid. Check if blank or invalid format.");
            }

            rentCar();
        } catch (InvalidRentException e) { // general error fallback
            JOptionPane.showMessageDialog(this, e.getMessage(), "Invalid rent: The selected car is not available.", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rentCarButtonActionPerformed

    // CAR COMBO BOX : RENT A CAR : SELECT CAR CHOICE
    private void rentCarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarComboActionPerformed
        updateRateNumField();
    }//GEN-LAST:event_rentCarComboActionPerformed

    // CLEAR RENT BUTTON : RENT A CAR : CLEAR INPUT DATA
    private void rentClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentClearButtonActionPerformed
        clearRentFields();
    }//GEN-LAST:event_rentClearButtonActionPerformed

    // ----------- EVENTS END ----------------
    // ----------- FUNCTIONS  START-----------
    // GET RATE PER DAY : GLOBAL : GETS APPROPRIATE RATE OF THE CARS
    private int getRatePerDay(String selectedCar) {
        switch (selectedCar) {
            case "Vios":
                return 2000;
            case "Avanza":
                return 4000;
            case "Corolla":
                return 5000;
            case "Innova":
                return 7000;
            case "Hilux":
                return 9000;
            case "Fortuner":
                return 10000;
            default:
                return 0; // Default rate if the selected car is not recognized
        }
    }

    // GET CAR INDEX : GLOBAL : GET INDEX OF CARS
    private int getCarIndex(String selectedCar) {
        switch (selectedCar) {
            case "Vios":
                return 0;
            case "Avanza":
                return 1;
            case "Corolla":
                return 2;
            case "Innova":
                return 3;
            case "Hilux":
                return 4;
            case "Fortuner":
                return 5;
            default:
                return -1;
        }
    }

    // UPDATE STATUS TABLE : STATUS TABLE : UPDATES TABLE VALUES
    private void updateStatusTable(String model, boolean isRented, String tenant) {
        int rowIndex = getCarRowIndex(model);
        statusTable.setValueAt(model, rowIndex, 0);

        // Check if isRented is true, set "True"; otherwise, set null for a blank spot
        statusTable.setValueAt(isRented ? "True" : null, rowIndex, 1);

        statusTable.setValueAt(tenant, rowIndex, 2);
    }

    // GET CAR ROW INDEX : STATUS TABLE : RETURN INDEX OF CAR IN TABLE ROW
    private int getCarRowIndex(String model) {
        for (int i = 0; i < statusTable.getRowCount(); i++) {
            if (statusTable.getValueAt(i, 0).equals(model)) {
                return i;
            }
        }
        return -1;
    }

    // CLEAR RENT BUTTON : RENT A CAR : CLEAR INPUT DATA FOR ALL FIELDS
    private void clearRentFields() {
        rentNameField.setText(null);
        rentDaysField.setText(null);
        rentAmountField.setText(null);
        rentTotalField.setText(null);
        rentChangeField.setText(null);
    }

    // UPDATE RATE NUM FIELD : RENT A CAR : UPDATES FIELD FOR CAR RATE UPON SELECTION
    private void updateRateNumField() {
        String selectedCar = (String) rentCarCombo.getSelectedItem();
        int ratePerDay = getRatePerDay(selectedCar);
        rateNumField.setText(Integer.toString(ratePerDay));
    }

    // CALCULATE RENT TOTAL : RENT A CAR : GET TOTAL RENT
    private void calculateRentTotal() {
        try {
            // get days from daysRentField input
            int days = Integer.parseInt(rentDaysField.getText());

            // if days are greater than 0
            if (days > 0) {
                // set rate based on model
                String selectedCar = (String) rentCarCombo.getSelectedItem();
                int ratePerDay = getRatePerDay(selectedCar);

                // calculate total rent days multiplied by rent
                int totalRent = days * ratePerDay;
                rentTotalField.setText(Integer.toString(totalRent));
                rateNumField.setText(Integer.toString(ratePerDay));
            } else { // if days is 0 or less
                rentTotalField.setText("Invalid day number");
            }
        } // general fallback error
        catch (NumberFormatException e) {
            rentTotalField.setText("Invalid input");
        }
    }

    // CALCULATE CHANGE : RENT A CAR : INPUT COMPLETE RENT
    private void calculateChange() {
        try {
            int amountPaid = Integer.parseInt(rentAmountField.getText());
            int totalRent = Integer.parseInt(rentTotalField.getText());

            if (amountPaid >= totalRent) {
                int change = amountPaid - totalRent;
                rentChangeField.setText(Integer.toString(change));
            } else {
                rentChangeField.setText("Insufficient amount");
            }
        } catch (NumberFormatException e) {
            rentChangeField.setText("Invalid format");
        }
    }

    // RENT CAR : RENT A CAR : INPUT COMPLETE RENT
    private void rentCar() throws InvalidRentException {

        // declare data inputs
        String name = rentNameField.getText();
        String selectedCar = (String) rentCarCombo.getSelectedItem();
        int days = Integer.parseInt(rentDaysField.getText());
        int rateNum = Integer.parseInt(rateNumField.getText());
        int totalRent = Integer.parseInt(rentTotalField.getText());
        int amountPaid = Integer.parseInt(rentAmountField.getText());
        int change = Integer.parseInt(rentChangeField.getText());

        // check if the selected car is available
        int carIndex = getCarIndex(selectedCar);
        if (carIndex != -1) {
            // update car availability
            carAvailability.rentCar(carIndex, name);
            // record the tentant name
            rentedCarCustomers[carIndex] = name;

            // JOptionPane rent success pop up
            JOptionPane.showMessageDialog(this,
                    "Rent successful!"
                    + "\nReciept is printed to file!"
                    + "\n"
                    + "\nName : " + name
                    + "\nModel : " + selectedCar
                    + "\nRate per day : " + rateNum
                    + "\nDay/s to Rent : " + days
                    + "\nRent Total : " + totalRent
                    + "\nAmount : " + amountPaid
                    + "\nChange Tendered : " + change,
                    "Rent Successful", JOptionPane.INFORMATION_MESSAGE);

            // Write user inputs to a .txt file
            writeToFile(name, selectedCar, days, rateNum, totalRent, amountPaid, change);
        } else {
            // Display a message if the selected car is not available
            throw new InvalidRentException("Sorry, the selected car is not available.");
        }

        // update Status Table
        updateStatusTable(selectedCar, true, name);
    }

    // WRITE TO FILE : RENT A CAR : OUTPUTS RENT TO FILE
    private void writeToFile(String name, String car, int days, int rateNum, int totalRent, int amountPaid, int change) {
        try {
            File outputFile = new File(name + "_rent-reciept.txt");
            BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile, true));

            // Append user inputs to the file
            writer.write("----- RENT RECIEPT -----\n");
            writer.write("Name : " + name + "\n");
            writer.write("Model : " + car + "\n");
            writer.write("Rate per day : " + rateNum + "\n");
            writer.write("Day/s Rented : " + days + "\n");
            writer.write("Rent Total : " + totalRent + "\n");
            writer.write("Amount : " + amountPaid + "\n");
            writer.write("Change Tendered : " + change + "\n\n");
            writer.close();

        } catch (IOException e) { // in the event such exceptions can occur
            e.printStackTrace();
        }
    }

    // RETURN CAR : RETURN A CAR : INPUT RETURN OPERATION
    private void returnCar() throws InvalidReturnException {

        // initialize variables
        String name = returnNameField.getText();
        String selectedCar = (String) returnCarCombo.getSelectedItem();
        int carIndex = getCarIndex(selectedCar);

        // check if name and model match
        if (carIndex != -1) {
            // update car availability
            carAvailability.returnCar(carIndex, name, selectedCar);
            // Display successful return popup
            JOptionPane.showMessageDialog(this,
                    "Return successful!"
                    + "\nReciept is printed to file!"
                    + "\n"
                    + "\nName : " + name
                    + "\nModel : " + selectedCar,
                    "Return Successful", JOptionPane.INFORMATION_MESSAGE);
            // Write return transaction to a file
            writeReturnTransactionToFile(name, selectedCar);
        } else {
            // Display a message if the car cannot be returned
            throw new InvalidReturnException("Sorry, unable to complete return. Try checking fields");
        }
        // update Status Table
        updateStatusTable(selectedCar, false, null);
    }

    // WRITE RETURN TRANSACTION TO FILE : RETURN A CAR : OUTPUT RETURN RECIEPT
    private void writeReturnTransactionToFile(String name, String car) {
        try {
            File returnFile = new File(name + "_return-reciept.txt");
            BufferedWriter writer = new BufferedWriter(new FileWriter(returnFile, true));

            // Append return transaction details to the file
            writer.write("----- RETURN RECIEPT -----\n");
            writer.write("Name : " + name + "\n");
            writer.write("Model : " + car + "\n\n");
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    // ----------- FUNCTIONS  END -----------
    public static void main(String[] args) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AlgoFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel avanzaEngineLabel;
    public javax.swing.JLabel avanzaEngineValuesLabel;
    public javax.swing.JLabel avanzaHeightLabel;
    public javax.swing.JLabel avanzaHeightValuesLabel;
    public javax.swing.JLabel avanzaHorsepowerLabel;
    public javax.swing.JLabel avanzaHorsepowerValuesLabel;
    public javax.swing.JLabel avanzaIMGLabel;
    public javax.swing.JLabel avanzaLengthLabel;
    public javax.swing.JLabel avanzaLengthValueslabel;
    public javax.swing.JLabel avanzaSeatingCapLabel;
    public javax.swing.JLabel avanzaSeatingCapValuesLabel;
    public javax.swing.JLabel avanzaSpecsLabel;
    public javax.swing.JLabel avanzaTorqueLabel;
    public javax.swing.JLabel avanzaTorqueValuesLabel;
    public javax.swing.JLabel avanzaTransmissionLabel;
    public javax.swing.JLabel avanzaTransmissionValuesLabel;
    public javax.swing.JLabel avanzaValuesLabel;
    public javax.swing.JLabel avanzaWidthValuesLabel;
    public javax.swing.JLabel avanzaWidthlabel;
    public javax.swing.JLabel corollaEngineLabel;
    public javax.swing.JLabel corollaEngineValuesLabel;
    public javax.swing.JLabel corollaHeightLabel;
    public javax.swing.JLabel corollaHeightValuesLabel;
    public javax.swing.JLabel corollaHorsepowerLabel;
    public javax.swing.JLabel corollaHorsepowerValuesLabel;
    public javax.swing.JLabel corollaIMGLabel;
    public javax.swing.JLabel corollaLengthLabel;
    public javax.swing.JLabel corollaLengthValuesLabel;
    public javax.swing.JLabel corollaSeatingCapLabel;
    public javax.swing.JLabel corollaSeatingCapValuesLabel;
    public javax.swing.JLabel corollaSpecsLabel;
    public javax.swing.JLabel corollaTorqueLabel;
    public javax.swing.JLabel corollaTorqueValuesLabel;
    public javax.swing.JLabel corollaTransmissionLabel;
    public javax.swing.JLabel corollaTransmissionValuesLabel;
    public javax.swing.JLabel corollaValuesLabel;
    public javax.swing.JLabel corollaWidthLabel;
    public javax.swing.JLabel corollaWidthValuesLabel;
    public javax.swing.JLabel fortunerEngineLabel;
    public javax.swing.JLabel fortunerEngineValuesLabel;
    public javax.swing.JLabel fortunerHeightLabel;
    public javax.swing.JLabel fortunerHeightValuesLabel;
    public javax.swing.JLabel fortunerHorsepowerLabel;
    public javax.swing.JLabel fortunerHorsepowerValuesLabel;
    public javax.swing.JLabel fortunerIMGLabel;
    public javax.swing.JLabel fortunerLengthLabel;
    public javax.swing.JLabel fortunerLengthValuesLabel;
    public javax.swing.JLabel fortunerSeatingCapLabel;
    public javax.swing.JLabel fortunerSeatingCapValuesLabel;
    public javax.swing.JLabel fortunerSpecsLabel;
    public javax.swing.JLabel fortunerTorqueLabel;
    public javax.swing.JLabel fortunerTorqueValuesLabel;
    public javax.swing.JLabel fortunerTransmissionLabel;
    public javax.swing.JLabel fortunerTransmissionValuesLabel;
    public javax.swing.JLabel fortunerValuesLabel;
    public javax.swing.JLabel fortunerWidthLabel;
    public javax.swing.JLabel fortunerWidthValuesLabel;
    public javax.swing.JLabel heightValuesLabel3;
    public javax.swing.JLabel hiluxEngineLabel;
    public javax.swing.JLabel hiluxEngineValuesLabel;
    public javax.swing.JLabel hiluxHeightLabel;
    public javax.swing.JLabel hiluxHeightValuesLabel;
    public javax.swing.JLabel hiluxHorsepowerLabel;
    public javax.swing.JLabel hiluxHorsepowerValuesLabel;
    public javax.swing.JLabel hiluxIMGLabel;
    public javax.swing.JLabel hiluxLengthLabel;
    public javax.swing.JLabel hiluxLengthValuesLabel;
    public javax.swing.JLabel hiluxSeatingCapLabel;
    public javax.swing.JLabel hiluxSeatingCapValuesLabel;
    public javax.swing.JLabel hiluxSpecsLabel;
    public javax.swing.JLabel hiluxTorqueLabel;
    public javax.swing.JLabel hiluxTorqueValuesLabel;
    public javax.swing.JLabel hiluxTransmissionLabel;
    public javax.swing.JLabel hiluxTransmissionValuesLabel;
    public javax.swing.JLabel hiluxValuesLabel;
    public javax.swing.JLabel hiluxWidthLabel;
    public javax.swing.JLabel hiluxWidthValuesLabel;
    public javax.swing.JLabel innovaEngineLabel;
    public javax.swing.JLabel innovaEngineValuesLabel;
    public javax.swing.JLabel innovaHeightLabel;
    public javax.swing.JLabel innovaHorsepowerLabel3;
    public javax.swing.JLabel innovaHorsepowerValuesLabel;
    public javax.swing.JLabel innovaIMGLabel;
    public javax.swing.JLabel innovaLengthLabel;
    public javax.swing.JLabel innovaLengthValuesLabel;
    public javax.swing.JLabel innovaSeatingCapLabel;
    public javax.swing.JLabel innovaSeatingCapValuesLabel;
    public javax.swing.JLabel innovaSpecsLabel;
    public javax.swing.JLabel innovaTorqueLabel;
    public javax.swing.JLabel innovaTorqueValuesLabel;
    public javax.swing.JLabel innovaTransmissionLabel;
    public javax.swing.JLabel innovaTransmissionValuesLabel;
    public javax.swing.JLabel innovaValuesLabel;
    public javax.swing.JLabel innovaWidthLabel;
    public javax.swing.JLabel innovaWidthValuesLabel;
    public javax.swing.JTabbedPane mainPanel;
    public javax.swing.JLabel rateHeaderLabel;
    public javax.swing.JTextField rateNumField;
    public javax.swing.JPanel rentACarPanel;
    public javax.swing.JTextField rentAmountField;
    public javax.swing.JLabel rentAmountLabel;
    public javax.swing.JButton rentCarButton;
    public javax.swing.JComboBox<String> rentCarCombo;
    public javax.swing.JButton rentChangeButton;
    public javax.swing.JTextField rentChangeField;
    public javax.swing.JLabel rentChangeLabel;
    public javax.swing.JButton rentClearButton;
    public javax.swing.JTextField rentDaysField;
    public javax.swing.JLabel rentDaysLabel;
    public javax.swing.JLabel rentModelLabel;
    public javax.swing.JTextField rentNameField;
    public javax.swing.JLabel rentNameLabel;
    public javax.swing.JButton rentTotalButton;
    public javax.swing.JTextField rentTotalField;
    public javax.swing.JLabel rentTotalLabel;
    public javax.swing.JPanel returnACarPanel;
    public javax.swing.JButton returnButton;
    public javax.swing.JComboBox<String> returnCarCombo;
    public javax.swing.JLabel returnModelLabel;
    public javax.swing.JTextField returnNameField;
    public javax.swing.JLabel returnNameLabel;
    public javax.swing.JScrollPane statusPane;
    public javax.swing.JPanel statusPanel;
    public javax.swing.JTable statusTable;
    public javax.swing.JLabel titleHeader;
    public javax.swing.JPanel viewCarPanel;
    public javax.swing.JPanel viewNestedAvanzaPanel;
    public javax.swing.JTabbedPane viewNestedCarTab;
    public javax.swing.JPanel viewNestedCorollaPanel;
    public javax.swing.JPanel viewNestedFortunerPanel;
    public javax.swing.JPanel viewNestedHiluxPanel;
    public javax.swing.JPanel viewNestedInnovaPanel;
    public javax.swing.JPanel viewNestedViosPanel;
    public javax.swing.JLabel viosEngineLabel;
    public javax.swing.JLabel viosEngineValuesLabel;
    public javax.swing.JLabel viosHeightLabel;
    public javax.swing.JLabel viosHeightValuesLabel;
    public javax.swing.JLabel viosHorsepowerLabel;
    public javax.swing.JLabel viosHorsepowerValuesLabel;
    public javax.swing.JLabel viosIMGLabel;
    public javax.swing.JLabel viosLengthLabel;
    public javax.swing.JLabel viosLengthValuesLabel;
    public javax.swing.JLabel viosSeatingCapLabel;
    public javax.swing.JLabel viosSeatingCapValuesLabel;
    public javax.swing.JLabel viosSpecsLabel;
    public javax.swing.JLabel viosTorqueLabel;
    public javax.swing.JLabel viosTorqueValuesLabel;
    public javax.swing.JLabel viosTransmissionLabel;
    public javax.swing.JLabel viosTransmissionValuesLabel;
    public javax.swing.JLabel viosValuesLabel;
    public javax.swing.JLabel viosVidthValuesLabel;
    public javax.swing.JLabel viosWidthLabel;
    // End of variables declaration//GEN-END:variables
}
