package algomotors2;

import javax.swing.*;
import java.io.*;

public class AlgoFrame extends javax.swing.JFrame {

    // AlgoFrame constructor
    public AlgoFrame() {
        initComponents(); // loads initComponents constructor
        int carNum = 6; // There are 6 car types
        rentedCarCustomers = new String[carNum];
        carAvailability = new CarAvailability(carNum);
        updateRateNumField();
    }

    private CarAvailability carAvailability;
    private String[] rentedCarCustomers;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modelRentLabel1 = new javax.swing.JLabel();
        carComboBox1 = new javax.swing.JComboBox<>();
        mainPanel = new javax.swing.JTabbedPane();
        viewCarPanel = new javax.swing.JPanel();
        viewNestedCarTab = new javax.swing.JTabbedPane();
        viewNestedViosPanel = new javax.swing.JPanel();
        viewNestedAvanzaPanel = new javax.swing.JPanel();
        viewNestedCorollaPanel = new javax.swing.JPanel();
        viewNestedInnovaPanel = new javax.swing.JPanel();
        viewNestedHiluxPanel = new javax.swing.JPanel();
        viewNestedFortunerPanel = new javax.swing.JPanel();
        rentACarPanel = new javax.swing.JPanel();
        nameRentLabel = new javax.swing.JLabel();
        nameRentField = new javax.swing.JTextField();
        modelRentLabel = new javax.swing.JLabel();
        carComboBox = new javax.swing.JComboBox<>();
        rentCarButton = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        daysRentLabel = new javax.swing.JLabel();
        daysRentField = new javax.swing.JTextField();
        rateHeaderLabel = new javax.swing.JLabel();
        rateNumField = new javax.swing.JTextField();
        rentTotalField = new javax.swing.JTextField();
        changeNumField = new javax.swing.JTextField();
        rentTotalButton = new javax.swing.JButton();
        changeNumButton = new javax.swing.JButton();
        rentTotalLabel = new javax.swing.JLabel();
        changeNumLabel = new javax.swing.JLabel();
        clearRentButton = new javax.swing.JButton();
        returnACarPanel = new javax.swing.JPanel();
        returnModelLabel = new javax.swing.JLabel();
        returnCarCombo = new javax.swing.JComboBox<>();
        nameReturnLabel = new javax.swing.JLabel();
        returnNameField = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTable = new javax.swing.JTable();
        titleHeader = new javax.swing.JLabel();

        modelRentLabel1.setText("Model");

        carComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vios", "Avanza", "Corolla", "Innova", "Hilux", "Fortuner" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algo Motors");

        javax.swing.GroupLayout viewNestedViosPanelLayout = new javax.swing.GroupLayout(viewNestedViosPanel);
        viewNestedViosPanel.setLayout(viewNestedViosPanelLayout);
        viewNestedViosPanelLayout.setHorizontalGroup(
            viewNestedViosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        viewNestedViosPanelLayout.setVerticalGroup(
            viewNestedViosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        viewNestedCarTab.addTab("Vios", viewNestedViosPanel);

        javax.swing.GroupLayout viewNestedAvanzaPanelLayout = new javax.swing.GroupLayout(viewNestedAvanzaPanel);
        viewNestedAvanzaPanel.setLayout(viewNestedAvanzaPanelLayout);
        viewNestedAvanzaPanelLayout.setHorizontalGroup(
            viewNestedAvanzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        viewNestedAvanzaPanelLayout.setVerticalGroup(
            viewNestedAvanzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        viewNestedCarTab.addTab("Avanza", viewNestedAvanzaPanel);

        javax.swing.GroupLayout viewNestedCorollaPanelLayout = new javax.swing.GroupLayout(viewNestedCorollaPanel);
        viewNestedCorollaPanel.setLayout(viewNestedCorollaPanelLayout);
        viewNestedCorollaPanelLayout.setHorizontalGroup(
            viewNestedCorollaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        viewNestedCorollaPanelLayout.setVerticalGroup(
            viewNestedCorollaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        viewNestedCarTab.addTab("Corolla", viewNestedCorollaPanel);

        javax.swing.GroupLayout viewNestedInnovaPanelLayout = new javax.swing.GroupLayout(viewNestedInnovaPanel);
        viewNestedInnovaPanel.setLayout(viewNestedInnovaPanelLayout);
        viewNestedInnovaPanelLayout.setHorizontalGroup(
            viewNestedInnovaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        viewNestedInnovaPanelLayout.setVerticalGroup(
            viewNestedInnovaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        viewNestedCarTab.addTab("Innova", viewNestedInnovaPanel);

        javax.swing.GroupLayout viewNestedHiluxPanelLayout = new javax.swing.GroupLayout(viewNestedHiluxPanel);
        viewNestedHiluxPanel.setLayout(viewNestedHiluxPanelLayout);
        viewNestedHiluxPanelLayout.setHorizontalGroup(
            viewNestedHiluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        viewNestedHiluxPanelLayout.setVerticalGroup(
            viewNestedHiluxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        viewNestedCarTab.addTab("Hilux", viewNestedHiluxPanel);

        javax.swing.GroupLayout viewNestedFortunerPanelLayout = new javax.swing.GroupLayout(viewNestedFortunerPanel);
        viewNestedFortunerPanel.setLayout(viewNestedFortunerPanelLayout);
        viewNestedFortunerPanelLayout.setHorizontalGroup(
            viewNestedFortunerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        viewNestedFortunerPanelLayout.setVerticalGroup(
            viewNestedFortunerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        viewNestedCarTab.addTab("Fortuner", viewNestedFortunerPanel);

        javax.swing.GroupLayout viewCarPanelLayout = new javax.swing.GroupLayout(viewCarPanel);
        viewCarPanel.setLayout(viewCarPanelLayout);
        viewCarPanelLayout.setHorizontalGroup(
            viewCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewNestedCarTab)
                .addContainerGap())
        );
        viewCarPanelLayout.setVerticalGroup(
            viewCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewNestedCarTab)
                .addContainerGap())
        );

        mainPanel.addTab("View Cars", viewCarPanel);

        nameRentLabel.setText("Name");

        modelRentLabel.setText("Model");

        carComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vios", "Avanza", "Corolla", "Innova", "Hilux", "Fortuner" }));
        carComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carComboBoxActionPerformed(evt);
            }
        });

        rentCarButton.setText("Rent Car");
        rentCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentCarButtonActionPerformed(evt);
            }
        });

        amountLabel.setText("Amount");

        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        daysRentLabel.setText("Day/s to Rent");

        daysRentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysRentFieldActionPerformed(evt);
            }
        });

        rateHeaderLabel.setText("Rate per day");

        rateNumField.setEditable(false);

        rentTotalField.setEditable(false);

        changeNumField.setEditable(false);

        rentTotalButton.setText("Get Rent");
        rentTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentTotalButtonActionPerformed(evt);
            }
        });

        changeNumButton.setText("Get Change");
        changeNumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNumButtonActionPerformed(evt);
            }
        });

        rentTotalLabel.setText("Rent Total");

        changeNumLabel.setText("Change Tendered");

        clearRentButton.setText("Clear All Fields");
        clearRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearRentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentACarPanelLayout = new javax.swing.GroupLayout(rentACarPanel);
        rentACarPanel.setLayout(rentACarPanelLayout);
        rentACarPanelLayout.setHorizontalGroup(
            rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentACarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameRentLabel)
                    .addComponent(modelRentLabel)
                    .addComponent(daysRentLabel)
                    .addComponent(amountLabel)
                    .addComponent(rentTotalLabel)
                    .addComponent(changeNumLabel))
                .addGap(59, 59, 59)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentACarPanelLayout.createSequentialGroup()
                        .addComponent(rentTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nameRentField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentACarPanelLayout.createSequentialGroup()
                        .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(rentACarPanelLayout.createSequentialGroup()
                                .addComponent(carComboBox, 0, 174, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(rateHeaderLabel))
                            .addGroup(rentACarPanelLayout.createSequentialGroup()
                                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(daysRentField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(changeNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(changeNumButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(rentTotalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rateNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(rentACarPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(rentCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(clearRentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rentACarPanelLayout.setVerticalGroup(
            rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentACarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRentLabel)
                    .addComponent(nameRentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelRentLabel)
                    .addComponent(carComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateHeaderLabel)
                    .addComponent(rateNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daysRentLabel)
                    .addComponent(daysRentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentTotalButton))
                .addGap(18, 18, 18)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentTotalLabel))
                .addGap(32, 32, 32)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeNumButton))
                .addGap(18, 18, 18)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeNumLabel)
                    .addComponent(changeNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(rentACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearRentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        mainPanel.addTab("Rent A Car", rentACarPanel);

        returnModelLabel.setText("Model");

        returnCarCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vios", "Avanza", "Corolla", "Innova", "Hilux", "Fortuner" }));

        nameReturnLabel.setText("Name");

        returnButton.setText("Return Car");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnACarPanelLayout = new javax.swing.GroupLayout(returnACarPanel);
        returnACarPanel.setLayout(returnACarPanelLayout);
        returnACarPanelLayout.setHorizontalGroup(
            returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnACarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnACarPanelLayout.createSequentialGroup()
                        .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(returnACarPanelLayout.createSequentialGroup()
                        .addGroup(returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnModelLabel)
                            .addComponent(nameReturnLabel))
                        .addGap(82, 82, 82)
                        .addGroup(returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnACarPanelLayout.createSequentialGroup()
                                .addComponent(returnCarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 309, Short.MAX_VALUE))
                            .addComponent(returnNameField))))
                .addContainerGap())
        );
        returnACarPanelLayout.setVerticalGroup(
            returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnACarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameReturnLabel)
                    .addComponent(returnNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(returnACarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnModelLabel)
                    .addComponent(returnCarCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        mainPanel.addTab("Return A Car", returnACarPanel);

        statusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Vios", null, null},
                {"Avanza", null, null},
                {"Corolla", null, null},
                {"Innova", null, null},
                {"Hilux", null, null},
                {"Fortuner", null, null}
            },
            new String [] {
                "Model", "Is Rented", "Tenant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(statusTable);

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        mainPanel.addTab("Status Panel", statusPanel);

        titleHeader.setText("Algo Motors System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleHeader)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleHeader)
                .addGap(18, 18, 18)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * EVENTS START
     *
     */
    // -------------------------------------------
    // RETURN BUTTON : OUTPUT RETURNED CAR
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        try {
            // Check if nameReturnField is not blank
            if (returnNameField.getText().trim().isEmpty()) {
                throw new InvalidReturnException("Name cannot be blank.");
            }

            returnCar();
        } catch (InvalidReturnException e) {
            // Handle the exception, e.g., display an error message
            JOptionPane.showMessageDialog(this, e.getMessage(), "Invalid Return", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_returnButtonActionPerformed

    // CHANGE NUM BUTTON : RENT A CAR : OUTPUT CHANGE FROM AMOUNT
    private void changeNumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNumButtonActionPerformed
        calculateChange();
    }//GEN-LAST:event_changeNumButtonActionPerformed

    // RENT TOTAL BUTTON : RENT A CAR : OUTPUT RENT
    private void rentTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentTotalButtonActionPerformed
        calculateRentTotal(); // part of calculateRentTotal()
    }//GEN-LAST:event_rentTotalButtonActionPerformed

    // DAYS RENT FIELD : RENT A CAR : INPUT HOW MANY DAYS TO RENT
    private void daysRentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysRentFieldActionPerformed
        calculateRentTotal(); // part of calculateRentTotal()
    }//GEN-LAST:event_daysRentFieldActionPerformed

    // AMOUNT FIELD : RENT A CAR :  INPUT HOW MUCH TO PAY FOR
    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        calculateChange();
    }//GEN-LAST:event_amountFieldActionPerformed

    // RENT CAR BUTTON : RENT A CAR : OUTPUT THE RENT SUCCESS OUTPUT
    private void rentCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentCarButtonActionPerformed
        // try multiple exceptions
        try {

            // Check if name is not blank
            if (nameRentField.getText().trim().isEmpty()) {
                throw new InvalidRentException("Invalid. Check if blank or invalid format.");
            }

            // Check if daysRentField is neither blank, 0, nor invalid
            try {
                int days = Integer.parseInt(daysRentField.getText());
                if (days <= 0) {
                    throw new InvalidRentException("Days must be greater than 0.");
                }
            } catch (NumberFormatException e) {
                throw new InvalidRentException("Invalid. Must be whole numbers only.");
            }

            // Check if changeNumField is neither blank nor invalid
            try {
                int change = Integer.parseInt(changeNumField.getText());
            } catch (NumberFormatException e) {
                throw new InvalidRentException("Invalid. Check if blank or invalid format.");
            }

            rentCar();
        } catch (InvalidRentException e) { // general error fallback
            JOptionPane.showMessageDialog(this, e.getMessage(), "Invalid Rent", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_rentCarButtonActionPerformed
    // RENT CAR BUTTON END

    // CAR COMBO BOX : RENT A CAR : SELECT CAR CHOICE
    private void carComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carComboBoxActionPerformed
        updateRateNumField();
    }//GEN-LAST:event_carComboBoxActionPerformed

    // CLEAR RENT BUTTON : RENT A CAR : CLEAR INPUT DATA
    private void clearRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearRentButtonActionPerformed
        clearRentFields();
    }//GEN-LAST:event_clearRentButtonActionPerformed

    /**
     *
     * EVENTS END
     *
     */
    // ----------- FUNCTIONS -----------
    /**
     *
     * GLOBAL START 
     *
     */
    // GET RATE PER DAY : GETS APPROPRIATE RATE OF THE CARS
    private int getRatePerDay(String selectedCar) {
        switch (selectedCar) {
            case "Vios":
                return 2000;
            case "Avanza":
                return 4000;
            case "Corolla":
                return 5000;
            case "Innova":
                return 7000;
            case "Hilux":
                return 9000;
            case "Fortuner":
                return 10000;
            default:
                return 0; // Default rate if the selected car is not recognized
        }
    }

    // GET CAR INDEX : GET INDEX OF CARS
    private int getCarIndex(String selectedCar) {
        switch (selectedCar) {
            case "Vios":
                return 0;
            case "Avanza":
                return 1;
            case "Corolla":
                return 2;
            case "Innova":
                return 3;
            case "Hilux":
                return 4;
            case "Fortuner":
                return 5;
            default:
                return -1;
        }
    }
   /**
     *
     * GLOBAL END
     *
     */
   /**
     *
     * STATUS TABLE START 
     *
     */
    private void updateStatusTable(String model, boolean isRented, String tenant) {
        int rowIndex = getCarRowIndex(model);
        statusTable.setValueAt(model, rowIndex, 0);

        // Check if isRented is true, set "True"; otherwise, set null for a blank spot
        statusTable.setValueAt(isRented ? "True" : null, rowIndex, 1);

        statusTable.setValueAt(tenant, rowIndex, 2);
    }

    private int getCarRowIndex(String model) {
        for (int i = 0; i < statusTable.getRowCount(); i++) {
            if (statusTable.getValueAt(i, 0).equals(model)) {
                return i;
            }
        }
        return -1;
    }
    /**
     *
     * STATUS TABLE END 
     *
     */
    /**
     *
     * RENT A CAR START
     *
     */
    // CLEAR RENT BUTTON : CLEAR INPUT DATA FOR ALL FIELDS
    private void clearRentFields() {
        nameRentField.setText(null);
        daysRentField.setText(null);
        amountField.setText(null);
        rentTotalField.setText(null);
        changeNumField.setText(null);
    }

    // UPDATE RATE NUM FIELD : UPDATES FIELD FOR CAR RATE UPON SELECTION
    private void updateRateNumField() {
        String selectedCar = (String) carComboBox.getSelectedItem();
        int ratePerDay = getRatePerDay(selectedCar);
        rateNumField.setText(Integer.toString(ratePerDay));
    }

    // CALCULATE RENT TOTAL : GET TOTAL RENT
    private void calculateRentTotal() {
        try {
            // get days from daysRentField input
            int days = Integer.parseInt(daysRentField.getText());

            // if days are greater than 0
            if (days > 0) {
                // set rate based on model
                String selectedCar = (String) carComboBox.getSelectedItem();
                int ratePerDay = getRatePerDay(selectedCar);

                // calculate total rent days multiplied by rent
                int totalRent = days * ratePerDay;
                rentTotalField.setText(Integer.toString(totalRent));
                rateNumField.setText(Integer.toString(ratePerDay));
            } else { // if days is 0 or less
                rentTotalField.setText("Invalid day number");
            }
        } // general fallback error
        catch (NumberFormatException e) {
            rentTotalField.setText("Invalid input");
        }
    }

    // CALCULATE CHANGE : INPUT COMPLETE RENT
    private void calculateChange() {
        try {
            int amountPaid = Integer.parseInt(amountField.getText());
            int totalRent = Integer.parseInt(rentTotalField.getText());

            if (amountPaid >= totalRent) {
                int change = amountPaid - totalRent;
                changeNumField.setText(Integer.toString(change));
            } else {
                changeNumField.setText("Insufficient amount");
            }
        } catch (NumberFormatException e) {
            changeNumField.setText("Invalid format");
        }
    }

    // RENT CAR : INPUT COMPLETE RENT
    private void rentCar() throws InvalidRentException {

        // declare data inputs
        String name = nameRentField.getText();
        String selectedCar = (String) carComboBox.getSelectedItem();
        int days = Integer.parseInt(daysRentField.getText());
        int totalRent = Integer.parseInt(rentTotalField.getText());
        int amountPaid = Integer.parseInt(amountField.getText());

        // check if the selected car is available
        int carIndex = getCarIndex(selectedCar);
        if (carIndex != -1) {
            // update car availability
            carAvailability.rentCar(carIndex, name);
            // record the tentant name
            rentedCarCustomers[carIndex] = name;

            // JOptionPane rent success pop up
            JOptionPane.showMessageDialog(this,
                    "Rent successful!"
                    + "\nReciept is printed to file!"
                    + "\n"
                    + "\nName: " + name
                    + "\nCar: " + selectedCar
                    + "\nDays Rented: " + days
                    + "\nTotal Rent: " + totalRent
                    + "\nAmount Paid: " + amountPaid
                    + "\nChange: " + changeNumField.getText(),
                    "Rent Successful", JOptionPane.INFORMATION_MESSAGE);

            // Write user inputs to a .txt file
            writeToFile(name, selectedCar, days, totalRent, amountPaid);
        } else {
            // Display a message if the selected car is not available
            throw new InvalidRentException("Sorry, the selected car is not available.");
        }

        // update Status Table
        updateStatusTable(selectedCar, true, name);
    }

    // WRITE TO FILE : OUTPUTS RENT TO FILE
    private void writeToFile(String name, String car, int days, int totalRent, int amountPaid) {
        try {
            File outputFile = new File(name + "_rent.txt");
            BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile, true));

            // Append user inputs to the file
            writer.write("----- RENT TRANSACTION -----\n");
            writer.write("Name: " + name + "\n");
            writer.write("Car: " + car + "\n");
            writer.write("Days Rented " + days + "\n");
            writer.write("Total Rent: " + totalRent + "\n");
            writer.write("Amount Paid: " + amountPaid + "\n\n");
            writer.close();

        } catch (IOException e) { // in the event such exceptions can occur
            e.printStackTrace();
        }
    }
   /**
     *
     * RENT A CAR END 
     *
     */
   /**
     *
     * RETURN A CAR START 
     *
     */ 
    // RETURN CAR : INPUT RETURN OPERATION
    private void returnCar() throws InvalidReturnException {

        // initialize variables
        String name = returnNameField.getText();
        String selectedCar = (String) returnCarCombo.getSelectedItem();
        int carIndex = getCarIndex(selectedCar);

        // check if name and model match
        if (carIndex != -1) {
            // update car availability
            carAvailability.returnCar(carIndex, name, selectedCar);
            // Display successful return popup
            JOptionPane.showMessageDialog(this,
                    "Return successful!"
                    + "\nReciept is printed to file!"
                    + "\n"
                    + "\nName: " + name
                    + "\nCar: " + selectedCar,
                    "Return Successful", JOptionPane.INFORMATION_MESSAGE);
            // Write return transaction to a file
            writeReturnTransactionToFile(name, selectedCar);
        } else {
            // Display a message if the car cannot be returned
            throw new InvalidReturnException("Sorry, unable to complete return. Try checking fields");
        }
        // update Status Table
        updateStatusTable(selectedCar, false, null);
    }

    private void writeReturnTransactionToFile(String name, String car) {
        try {
            File returnFile = new File(name + "_return.txt");
            BufferedWriter writer = new BufferedWriter(new FileWriter(returnFile, true));

            // Append return transaction details to the file
            writer.write("----- RENT TRANSACTION -----\n");
            writer.write("Name: " + name + "\n");
            writer.write("Car: " + car + "\n\n");

            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    /**
     *
     * RETURN A CAR END 
     *
     */

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AlgoFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField amountField;
    public javax.swing.JLabel amountLabel;
    public javax.swing.JComboBox<String> carComboBox;
    public javax.swing.JComboBox<String> carComboBox1;
    public javax.swing.JButton changeNumButton;
    public javax.swing.JTextField changeNumField;
    public javax.swing.JLabel changeNumLabel;
    public javax.swing.JButton clearRentButton;
    public javax.swing.JTextField daysRentField;
    public javax.swing.JLabel daysRentLabel;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane mainPanel;
    public javax.swing.JLabel modelRentLabel;
    public javax.swing.JLabel modelRentLabel1;
    public javax.swing.JTextField nameRentField;
    public javax.swing.JLabel nameRentLabel;
    public javax.swing.JLabel nameReturnLabel;
    public javax.swing.JLabel rateHeaderLabel;
    public javax.swing.JTextField rateNumField;
    public javax.swing.JPanel rentACarPanel;
    public javax.swing.JButton rentCarButton;
    public javax.swing.JButton rentTotalButton;
    public javax.swing.JTextField rentTotalField;
    public javax.swing.JLabel rentTotalLabel;
    public javax.swing.JPanel returnACarPanel;
    public javax.swing.JButton returnButton;
    public javax.swing.JComboBox<String> returnCarCombo;
    public javax.swing.JLabel returnModelLabel;
    public javax.swing.JTextField returnNameField;
    public javax.swing.JPanel statusPanel;
    public javax.swing.JTable statusTable;
    public javax.swing.JLabel titleHeader;
    private javax.swing.JPanel viewCarPanel;
    public javax.swing.JPanel viewNestedAvanzaPanel;
    public javax.swing.JTabbedPane viewNestedCarTab;
    public javax.swing.JPanel viewNestedCorollaPanel;
    public javax.swing.JPanel viewNestedFortunerPanel;
    public javax.swing.JPanel viewNestedHiluxPanel;
    public javax.swing.JPanel viewNestedInnovaPanel;
    public javax.swing.JPanel viewNestedViosPanel;
    // End of variables declaration//GEN-END:variables
}
